const labels = [
  { value: '101', label: 'Manhattan CD 1' },
  { value: '102', label: 'Manhattan CD 2' },
  { value: '103', label: 'Manhattan CD 3' },
  { value: '104', label: 'Manhattan CD 4' },
  { value: '105', label: 'Manhattan CD 5' },
  { value: '106', label: 'Manhattan CD 6' },
  { value: '107', label: 'Manhattan CD 7' },
  { value: '108', label: 'Manhattan CD 8' },
  { value: '109', label: 'Manhattan CD 9' },
  { value: '110', label: 'Manhattan CD 10' },
  { value: '111', label: 'Manhattan CD 11' },
  { value: '112', label: 'Manhattan CD 12' },

  { value: '201', label: 'Bronx CD 1' },
  { value: '202', label: 'Bronx CD 2' },
  { value: '203', label: 'Bronx CD 3' },
  { value: '204', label: 'Bronx CD 4' },
  { value: '205', label: 'Bronx CD 5' },
  { value: '206', label: 'Bronx CD 6' },
  { value: '207', label: 'Bronx CD 7' },
  { value: '208', label: 'Bronx CD 8' },
  { value: '209', label: 'Bronx CD 9' },
  { value: '210', label: 'Bronx CD 10' },
  { value: '211', label: 'Bronx CD 11' },
  { value: '212', label: 'Bronx CD 12' },

  { value: '301', label: 'Brooklyn CD 1' },
  { value: '302', label: 'Brooklyn CD 2' },
  { value: '303', label: 'Brooklyn CD 3' },
  { value: '304', label: 'Brooklyn CD 4' },
  { value: '305', label: 'Brooklyn CD 5' },
  { value: '306', label: 'Brooklyn CD 6' },
  { value: '307', label: 'Brooklyn CD 7' },
  { value: '308', label: 'Brooklyn CD 8' },
  { value: '309', label: 'Brooklyn CD 9' },
  { value: '310', label: 'Brooklyn CD 10' },
  { value: '311', label: 'Brooklyn CD 11' },
  { value: '312', label: 'Brooklyn CD 12' },
  { value: '313', label: 'Brooklyn CD 13' },
  { value: '314', label: 'Brooklyn CD 14' },
  { value: '315', label: 'Brooklyn CD 15' },
  { value: '316', label: 'Brooklyn CD 16' },
  { value: '317', label: 'Brooklyn CD 17' },
  { value: '318', label: 'Brooklyn CD 18' },

  { value: '401', label: 'Queens CD 1' },
  { value: '402', label: 'Queens CD 2' },
  { value: '403', label: 'Queens CD 3' },
  { value: '404', label: 'Queens CD 4' },
  { value: '405', label: 'Queens CD 5' },
  { value: '406', label: 'Queens CD 6' },
  { value: '407', label: 'Queens CD 7' },
  { value: '408', label: 'Queens CD 8' },
  { value: '409', label: 'Queens CD 9' },
  { value: '410', label: 'Queens CD 10' },
  { value: '411', label: 'Queens CD 11' },
  { value: '412', label: 'Queens CD 12' },
  { value: '413', label: 'Queens CD 13' },
  { value: '414', label: 'Queens CD 14' },

  { value: '501', label: 'Staten Island CD 1' },
  { value: '502', label: 'Staten Island CD 2' },
  { value: '503', label: 'Staten Island CD 3' },
];

export default labels;
