const asyncType = type => ({
  PENDING: `${type}_PENDING`,
  SUCCESS: `${type}_SUCCESS`,
  FAILURE: `${type}_FAILURE`,
});

// Carto & API
export const CARTO_REQUEST = 'CARTO_REQUEST';
export const FETCH_NYC_BOUNDS = asyncType('FETCH_NYC_BOUNDS');

// Modals
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// Auth
export const AUTH0_LOGIN = 'AUTH0_LOGIN';
export const AUTH0_LOGOUT = 'AUTH0_LOGOUT';
export const AUTH0_SIGNUP = 'AUTH0_SIGNUP';
export const LOAD_CREDENTIALS = 'LOAD_CREDENTIALS';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const DEAUTHORIZE_USER = 'DEAUTHORIZE_USER';
export const ENSURE_ACCESS = 'ENSURE_ACCESS';

// Facilities
export const FETCH_FACILITY_DETAILS = asyncType('FETCH_FACILITY_DETAILS');
export const FETCH_FACILITY_AGENCY_VALUES = asyncType('FETCH_FACILITY_AGENCY_VALUES');
export const FETCH_FACILITIES_TOTAL_COUNT = asyncType('FETCH_FACILITIES_TOTAL_COUNT');
export const FETCH_FACILITIES_SELECTED_COUNT = asyncType('FETCH_FACILITIES_SELECTED_COUNT');
export const SET_SELECTED_FACILITIES_FEATURES = 'SET_SELECTED_FACILITIES_FEATURES';
export const SET_FACILITIES_FILTERS = 'SET_FACILITIES_FILTERS';
export const SET_FACILITIES_FILTER_DIMENSION = 'SET_FACILITIES_FILTER_DIMENSION';
export const RESET_FACILITIES_FILTER = 'RESET_FACILITIES_FILTER';

// Facilities CP
export const FETCH_FACILITY_CP_DETAILS = asyncType('FETCH_FACILITY_CP_DETAILS');
export const FETCH_FACILITY_CP_AGENCY_VALUES = asyncType('FETCH_FACILITY_CP_AGENCY_VALUES');
export const FETCH_FACILITIES_CP_TOTAL_COUNT = asyncType('FETCH_FACILITIES_CP_TOTAL_COUNT');
export const FETCH_FACILITIES_CP_SELECTED_COUNT = asyncType('FETCH_FACILITIES_CP_SELECTED_COUNT');
export const SET_SELECTED_FACILITIES_CP_FEATURES = 'SET_SELECTED_FACILITIES_CP_FEATURES';
export const SET_FACILITIES_CP_FILTERS = 'SET_FACILITIES_CP_FILTERS';
export const SET_FACILITIES_CP_FILTER_DIMENSION = 'SET_FACILITIES_CP_FILTER_DIMENSION';
export const RESET_FACILITIES_CP_FILTER = 'RESET_FACILITIES_CP_FILTER';

// Capital Projects
export const FETCH_CAPITAL_PROJECT_DETAILS = asyncType('FETCH_CAPITAL_PROJECT_DETAILS');
export const FETCH_CAPITAL_PROJECT_BUDGETS = asyncType('FETCH_CAPITAL_PROJECT_BUDGETS');
export const FETCH_CAPITAL_PROJECT_COMMITMENTS = asyncType('FETCH_CAPITAL_PROJECT_COMMITMENTS');
export const FETCH_CAPITAL_PROJECTS_TOTAL_POINTS_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TOTAL_POINTS_COUNT');
export const FETCH_CAPITAL_PROJECTS_TOTAL_POLYGONS_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TOTAL_POLYGONS_COUNT');
export const FETCH_CAPITAL_PROJECTS_SELECTED_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_SELECTED_COUNT');
export const FETCH_COST_GROUP_DATA = asyncType('FETCH_COST_GROUP_DATA');
export const SET_CAPITAL_PROJECTS_FILTER_DIMENSION = 'SET_CAPITAL_PROJECTS_FILTER_DIMENSION';
export const RESET_CAPITAL_PROJECTS_FILTER = 'RESET_CAPITAL_PROJECTS_FILTER';
export const SET_SELECTED_CAPITAL_PROJECTS_FEATURES = 'SET_SELECTED_CAPITAL_PROJECTS_FEATURES';

// Capital Projects Table
export const FETCH_CAPITAL_PROJECT_TABLE_DETAILS = asyncType('FETCH_CAPITAL_PROJECT_TABLE_DETAILS');
export const FETCH_CAPITAL_PROJECTS_TABLE_TOTAL_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TABLE_TOTAL_COUNT');
export const FETCH_CAPITAL_PROJECTS_TABLE_SELECTED_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TABLE_SELECTED_COUNT');
export const SET_CAPITAL_PROJECTS_TABLE_FILTER_DIMENSION = 'SET_CAPITAL_PROJECTS_TABLE_FILTER_DIMENSION';
export const RESET_CAPITAL_PROJECTS_TABLE_FILTER = 'RESET_CAPITAL_PROJECTS_TABLE_FILTER';
export const SET_CAPITAL_PROJECTS_TABLE_FILTER_BY = 'SET_CAPITAL_PROJECTS_TABLE_FILTER_BY';
export const SET_CAPITAL_PROJECTS_TABLE_SORT = 'SET_CAPITAL_PROJECTS_TABLE_SORT';

// Capital Budget Requests
export const FETCH_CB_BUDGET_REQUEST_DETAILS = asyncType('FETCH_CB_BUDGET_REQUEST_DETAILS');
export const FETCH_CB_BUDGET_REQUESTS_TOTAL_COUNT = asyncType('FETCH_CB_BUDGET_REQUESTS_TOTAL_COUNT');
export const FETCH_CB_BUDGET_REQUESTS_SELECTED_COUNT = asyncType('FETCH_CB_BUDGET_REQUESTS_SELECTED_COUNT');
export const SET_CB_BUDGET_REQUESTS_FILTER_DIMENSION = 'SET_CB_BUDGET_REQUESTS_FILTER_DIMENSION';
export const RESET_CB_BUDGET_REQUESTS_FILTER = 'RESET_CB_BUDGET_REQUESTS_FILTER';

// Housing Development
export const FETCH_HOUSING_DEVELOPMENT_DETAILS = asyncType('FETCH_HOUSING_DEVELOPMENT_DETAILS');
export const FETCH_HOUSING_DEVELOPMENT_TOTAL_COUNT = asyncType('FETCH_HOUSING_DEVELOPMENT_TOTAL_COUNT');
export const FETCH_HOUSING_DEVELOPMENT_SELECTED_COUNT = asyncType('FETCH_HOUSING_DEVELOPMENT_SELECTED_COUNT');
export const SET_SELECTED_HOUSING_DEVELOPMENT_FEATURES = 'SET_SELECTED_HOUSING_DEVELOPMENT_FEATURES';
export const SET_HOUSING_DEVELOPMENT_SYMBOLOGY = 'SET_HOUSING_DEVELOPMENT_SYMBOLOGY';
export const SET_HOUSING_DEVELOPMENT_FILTER_DIMENSION = 'SET_HOUSING_DEVELOPMENT_FILTER_DIMENSION';
export const RESET_HOUSING_DEVELOPMENT_FILTER = 'RESET_HOUSING_DEVELOPMENT_FILTER';
