const asyncType = (type) => ({
  PENDING: `${type}_PENDING`,
  SUCCESS: `${type}_SUCCESS`,
  FAILURE: `${type}_FAILURE`,
});

// Carto & API
export const CARTO_REQUEST = 'CARTO_REQUEST';

// Facilities
export const FETCH_FACILITY_DETAILS = asyncType('FETCH_FACILITY_DETAILS');
export const FETCH_FACILITY_AGENCY_VALUES = asyncType('FETCH_FACILITY_AGENCY_VALUES');
export const FETCH_FACILITIES_TOTAL_COUNT = asyncType('FETCH_FACILITIES_TOTAL_COUNT');
export const FETCH_FACILITIES_SELECTED_COUNT = asyncType('FETCH_FACILITIES_SELECTED_COUNT');
export const SET_SELECTED_FACILITIES_FEATURES = 'SET_SELECTED_FACILITIES_FEATURES';
export const SET_FACILITIES_FILTERS = 'SET_FACILITIES_FILTERS';
export const SET_FACILITIES_FILTER_DIMENSION = 'SET_FACILITIES_FILTER_DIMENSION';
export const RESET_FACILITIES_FILTERS = 'RESET_FACILITIES_FILTERS';

// Capital Projects
export const FETCH_CAPITAL_PROJECT_DETAILS = asyncType('FETCH_CAPITAL_PROJECT_DETAILS');
export const FETCH_CAPITAL_PROJECT_BUDGETS = asyncType('FETCH_CAPITAL_PROJECT_BUDGETS');
export const FETCH_CAPITAL_PROJECT_COMMITMENTS = asyncType('FETCH_CAPITAL_PROJECT_COMMITMENTS');
export const FETCH_CAPITAL_PROJECTS_TOTAL_POINTS_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TOTAL_POINTS_COUNT');
export const FETCH_CAPITAL_PROJECTS_TOTAL_POLYGONS_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TOTAL_POLYGONS_COUNT');
export const FETCH_CAPITAL_PROJECTS_SELECTED_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_SELECTED_COUNT');
export const SET_CAPITAL_PROJECTS_FILTER_DIMENSION = 'SET_CAPITAL_PROJECTS_FILTER_DIMENSION';
export const RESET_CAPITAL_PROJECTS_FILTERS = 'RESET_CAPITAL_PROJECTS_FILTERS';
export const SET_SELECTED_CAPITAL_PROJECTS_FEATURES = 'SET_SELECTED_CAPITAL_PROJECTS_FEATURES';

// Capital Projects Table
export const FETCH_CAPITAL_PROJECT_TABLE_DETAILS = asyncType('FETCH_CAPITAL_PROJECT_TABLE_DETAILS');
export const FETCH_CAPITAL_PROJECTS_TABLE_TOTAL_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TABLE_TOTAL_COUNT');
export const FETCH_CAPITAL_PROJECTS_TABLE_SELECTED_COUNT = asyncType('FETCH_CAPITAL_PROJECTS_TABLE_SELECTED_COUNT');
export const SET_CAPITAL_PROJECTS_TABLE_FILTER_DIMENSION = 'SET_CAPITAL_PROJECTS_TABLE_FILTER_DIMENSION';
export const RESET_CAPITAL_PROJECTS_TABLE_FILTERS = 'RESET_CAPITAL_PROJECTS_TABLE_FILTERS';
export const SET_CAPITAL_PROJECTS_TABLE_FILTER_BY = 'SET_CAPITAL_PROJECTS_TABLE_FILTER_BY';
export const SET_CAPITAL_PROJECTS_TABLE_SORT = 'SET_CAPITAL_PROJECTS_TABLE_SORT';
